DROP TABLE IF EXISTS fpc_reviews CASCADE;
DROP TABLE IF EXISTS hod_reviews CASCADE;
DROP TABLE IF EXISTS student_submissions CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS fpc CASCADE;
DROP TABLE IF EXISTS hod CASCADE;
DROP TABLE IF EXISTS admin CASCADE;